spring:
  application.name: vortex-etl-api

  profiles:
    active: local
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3366/vortex_etl
    username: vortex
    password: vortex

  data:
    web.pageable:
      default-page-size: 10
      max-page-size: 100
      one-indexed-parameters: true

# Application related configurations
application:
  token:
    ttl: 360000 # 100 hours
    secret:

# Configuraciones de logging para ver las queries de JDBC
logging:
  level:
    org.springframework.data.jdbc: DEBUG